version: '3.'

services:
    web:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        container_name: web
        restart: always
        # command: ./scripts/start.sh
        environment:
            - DEBUG=False
            - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
            - ADMIN_USER=TEST
            - ADMIN_PASSWORD=TEST
        ports:
            - '0.0.0.0:8000:8000'
        volumes:
            - static:/app/staticfiles
        depends_on:
            - postgres

    postgres:
        image: postgres:17.5
        container_name: postgres
        command: postgres -c 'max_connections=1000'
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        ports:
            - '127.0.0.1:5432:5432'
        volumes:
            - .postgres:/var/lib/postgresql/data

volumes:
    postgres:
        external: false
    static:
        external: false
